version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db/your_project_name
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=your_project_name
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

