version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./src:/usr/src/app/src
      - ./migrations:/usr/src/app/migrations
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ROCKET_ENV=development
      - ROCKET_ADDRESS=0.0.0.0
    command: cargo watch -x run
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cargo-cache:
  target-cache:
